### ISSUE TITLE
DrawingPlayer-SelectWord-SeeWordOnScreen

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-client#13]
**Story:** As a drawing player, I want to select within three given words. After I selected one word, I want to keep that word on my screen so that I can draw based on it. 

**Acceptance Criteria:**
- [ ] There are three buttons with labels which display the three words provided by the backend API. 
- [ ] Before the drawing phase starts, the player can choose among 3 words by clicking one of the three buttons. There is no time limit on word selection phase. 
- [ ] In the word selection phase, the white board is disabled. Which means the player cannot paint at that time. 
- [ ] After the drawing player has clicked the word that he/she chooses, the drawing phase immediately begins. The timer starts to count down.  
- [ ] During the drawing phase, the drawing player can start painting on the white board. 
- [ ] The chosen word will stay on the screen so that the drawing player can see it while he/she is drawing.

**Development Tasks:**
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#72
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#73
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#74
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#75
