### ISSUE TITLE
DrawingPlayer-UsePen-DrawSubmit

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-client#14]
**Story:** As a drawing player, I want to use pen/brush to draw any shapes and submit my painting on time. 

**Acceptance Criteria:**
- [ ] After the drawing phase starts, there is a white board area which allows the drawing player to draw inside. 
- [ ] There is a pen icon on the whiteboard. After clicking the pen icon, the pen tool can be used to draw any shapes. 
- [ ] During the drawing phase, the player can draw freehand on the white board and see the painting instantly. 
- [ ] There is a submit button which allows the drawing player to submit painting within the preset time. After clicking the submit button, the painting is saved and submitted. The drawing player’s turn is finished. 
- [ ] If the preset time runs out, and the drawing player still hasn’t clicked the submit button.  What is on the whiteboard will be automatically sent to the backend. The drawing player’s turn is finished.
- [ ] When the drawing player’s turn ends (time runs out or clicked “Submit”),  the player cannot continue drawing. All tools for drawing will be disabled.

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#88
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#89
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#90
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#91
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#92
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#93
