### ISSUE TITLE
User-CreateNewGame-FindPlayer

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-client#8]
**Story:** As a logged-in user, I want to create a new game to look for other players to play with. 

**Acceptance Criteria:**
- [ ] In the Game Lobby page, a logged-in user can create a game room by clicking the “create” button. 
- [ ] After clicking the “create” button in the game lobby page, the user can enter the room name, and choose the game mode (2 players; 4 players), then he can click ”create” button to create a game room, or click “back” to turn back to the game lobby page. 
- [ ] The player who creates the room will be the owner. After the room is created, the owner will be redirected to the waiting page. 
- [ ] The other logged-in users can see the existed game rooms in the lobby and can click "Join" button to enter the room.
- [ ] The newly joined users will be redirected to the waiting page.
- [ ] Other users can only join the room which is still lack of players. If the room is full, the user cannot enter this game room. 

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#38
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#39
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#40
- [x] sopra-fs23-group-19/sopra-fs23-group-19-server#41
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#42
- [ ] sopra-fs23-group-19/sopra-fs23-group-19-server#43
